// Pokemon TCG Seed Data — Two Starter Decks (~120 cards total)
// Run via: node src/server/seed-pokemon.js
// Or imported by index.ts autoSeed

export const pokemonGameSeed = {
    id: 'pokemon-tcg',
    name: { en: 'Pokémon TCG', id: 'Pokémon TCG' },
    category: ['Card Game', 'Strategy', 'Collectible'],
    shortDescription: { en: 'The Pokémon Trading Card Game.', id: 'Permainan Kartu Koleksi Pokémon.' },
    description: {
        en: 'The Pokémon Trading Card Game is a collectible card game based on the Pokémon franchise. Players build decks of 60 cards featuring Pokémon, Trainer cards, and Energy cards, then battle to knock out their opponent\'s Pokémon and claim Prize cards.',
        id: 'Pokémon Trading Card Game adalah permainan kartu koleksi berdasarkan waralaba Pokémon. Pemain membangun dek berisi 60 kartu yang terdiri dari Pokémon, kartu Trainer, dan kartu Energi, lalu bertarung untuk mengalahkan Pokémon lawan dan mengambil kartu Hadiah.'
    },
    minPlayers: 2,
    maxPlayers: 2,
    playTime: 20,
    complexity: 3,
    designer: 'Tsunekazu Ishihara',
    yearPublished: 1996,
    mechanics: ['Hand Management', 'Card Drafting', 'Set Collection', 'Deck Building'],
    imageUrl: 'https://placehold.co/800x600/dc2626/fef2f2.png?text=Pokémon+TCG',
    howToPlay: {
        en: [
            'Each player builds a 60-card deck with Pokémon, Trainer, and Energy cards.',
            'Draw 7 cards. Place a Basic Pokémon face-down as your Active Pokémon.',
            'Place up to 5 Basic Pokémon on your Bench. Set aside 6 Prize cards.',
            'On your turn: Draw a card, play Basic Pokémon to Bench, attach one Energy, use Trainer cards, and attack.',
            'Knock out opponent\'s Pokémon by dealing damage equal to or exceeding their HP.',
            'Win by taking all 6 Prize cards, knocking out all opponent\'s Pokémon, or if opponent can\'t draw.'
        ],
        id: [
            'Setiap pemain membangun dek 60 kartu dengan Pokémon, Trainer, dan Energi.',
            'Ambil 7 kartu. Letakkan Pokémon Dasar tertutup sebagai Pokémon Aktif.',
            'Letakkan hingga 5 Pokémon Dasar di Bench. Sisihkan 6 kartu Hadiah.',
            'Pada giliran Anda: Ambil kartu, mainkan Pokémon Dasar, tempelkan satu Energi, gunakan Trainer, dan serang.',
            'Kalahkan Pokémon lawan dengan memberikan damage sama atau melebihi HP mereka.',
            'Menang dengan mengambil 6 kartu Hadiah, mengalahkan semua Pokémon lawan, atau lawan tidak bisa mengambil kartu.'
        ]
    },
    rules: [
        { title: { en: 'Energy', id: 'Energi' }, content: { en: 'You may attach one Energy card per turn to one of your Pokémon. Energy is required to use attacks.', id: 'Anda boleh menempelkan satu kartu Energi per giliran ke salah satu Pokémon Anda. Energi diperlukan untuk menggunakan serangan.' } },
        { title: { en: 'Evolution', id: 'Evolusi' }, content: { en: 'Place a Stage 1 Pokémon on a Basic Pokémon, or a Stage 2 on a Stage 1. You cannot evolve a Pokémon the same turn it was played.', id: 'Letakkan Pokémon Tahap 1 di atas Pokémon Dasar, atau Tahap 2 di atas Tahap 1. Anda tidak bisa mengevolusikan Pokémon di giliran yang sama saat dimainkan.' } },
        { title: { en: 'Retreat', id: 'Mundur' }, content: { en: 'Pay the Retreat Cost (discard Energy) to switch your Active Pokémon with one on your Bench.', id: 'Bayar Biaya Mundur (buang Energi) untuk menukar Pokémon Aktif dengan salah satu di Bench.' } }
    ],
    faq: [
        { q: { en: 'How many Prize cards do I take when I knock out a Pokémon?', id: 'Berapa kartu Hadiah yang saya ambil saat mengalahkan Pokémon?' }, a: { en: 'Usually 1, but Pokémon-EX and Pokémon-V give 2 Prize cards, and VMAX/VSTAR give 2-3.', id: 'Biasanya 1, tetapi Pokémon-EX dan Pokémon-V memberikan 2 kartu Hadiah, dan VMAX/VSTAR memberikan 2-3.' } },
        { q: { en: 'Can I have more than 4 copies of a card?', id: 'Bisakah saya memiliki lebih dari 4 salinan kartu?' }, a: { en: 'No, except for Basic Energy cards which have no copy limit.', id: 'Tidak, kecuali kartu Energi Dasar yang tidak memiliki batas salinan.' } }
    ]
};

// ──── Starter Deck 1: Blaze Storm (Fire/Fighting) ────
export const pokemonDeck1Cards = [
    // ─── FIRE POKÉMON ───
    { gameId: 'pokemon-tcg', name: { en: 'Charmander', id: 'Charmander' }, type: { en: 'Fire - Basic', id: 'Api - Dasar' }, effect: { en: 'Ember: Discard 1 Fire Energy. 30 damage.', id: 'Bara Api: Buang 1 Energi Api. 30 damage.' }, lore: { en: 'The flame on its tail shows the strength of its life force.', id: 'Api di ekornya menunjukkan kekuatan daya hidupnya.' }, imageUrl: 'https://placehold.co/400x560/ef4444/ffffff.png?text=Charmander', color: '#ef4444', hp: 70, attack: 30 },
    { gameId: 'pokemon-tcg', name: { en: 'Charmander', id: 'Charmander' }, type: { en: 'Fire - Basic', id: 'Api - Dasar' }, effect: { en: 'Ember: Discard 1 Fire Energy. 30 damage.', id: 'Bara Api: Buang 1 Energi Api. 30 damage.' }, lore: { en: 'The flame on its tail shows the strength of its life force.', id: 'Api di ekornya menunjukkan kekuatan daya hidupnya.' }, imageUrl: 'https://placehold.co/400x560/ef4444/ffffff.png?text=Charmander', color: '#ef4444', hp: 70, attack: 30 },
    { gameId: 'pokemon-tcg', name: { en: 'Charmeleon', id: 'Charmeleon' }, type: { en: 'Fire - Stage 1', id: 'Api - Tahap 1' }, effect: { en: 'Flamethrower: Discard 1 Energy. 70 damage.', id: 'Penyembur Api: Buang 1 Energi. 70 damage.' }, lore: { en: 'Tough fights could excite this Pokémon, causing it to spout flames.', id: 'Pertarungan sengit bisa membuatnya bersemangat dan menyemburkan api.' }, imageUrl: 'https://placehold.co/400x560/dc2626/ffffff.png?text=Charmeleon', color: '#dc2626', hp: 90, attack: 70 },
    { gameId: 'pokemon-tcg', name: { en: 'Charizard', id: 'Charizard' }, type: { en: 'Fire - Stage 2', id: 'Api - Tahap 2' }, effect: { en: 'Fire Blast: Discard 1 Energy. 150 damage.', id: 'Ledakan Api: Buang 1 Energi. 150 damage.' }, lore: { en: 'It spits fire hot enough to melt boulders. It may cause forest fires.', id: 'Semburan apinya cukup panas untuk melelehkan batu besar.' }, imageUrl: 'https://placehold.co/400x560/b91c1c/ffffff.png?text=Charizard', color: '#b91c1c', hp: 170, attack: 150 },
    { gameId: 'pokemon-tcg', name: { en: 'Vulpix', id: 'Vulpix' }, type: { en: 'Fire - Basic', id: 'Api - Dasar' }, effect: { en: 'Tail Whip: Opponent flips coin; if tails, can\'t attack next turn.', id: 'Kibasan Ekor: Lawan lempar koin; jika ekor, tidak bisa menyerang giliran berikutnya.' }, lore: { en: 'Its six beautiful tails become magnificently curled with age.', id: 'Enam ekor indahnya semakin bergelombang seiring usia.' }, imageUrl: 'https://placehold.co/400x560/f97316/ffffff.png?text=Vulpix', color: '#f97316', hp: 60, attack: 20 },
    { gameId: 'pokemon-tcg', name: { en: 'Vulpix', id: 'Vulpix' }, type: { en: 'Fire - Basic', id: 'Api - Dasar' }, effect: { en: 'Tail Whip: Opponent flips coin; if tails, can\'t attack next turn.', id: 'Kibasan Ekor: Lawan lempar koin; jika ekor, tidak bisa menyerang giliran berikutnya.' }, lore: { en: 'Its six beautiful tails become magnificently curled with age.', id: 'Enam ekor indahnya semakin bergelombang seiring usia.' }, imageUrl: 'https://placehold.co/400x560/f97316/ffffff.png?text=Vulpix', color: '#f97316', hp: 60, attack: 20 },
    { gameId: 'pokemon-tcg', name: { en: 'Ninetales', id: 'Ninetales' }, type: { en: 'Fire - Stage 1', id: 'Api - Tahap 1' }, effect: { en: 'Fire Mane: 90 damage. Flip coin; if heads, opponent is Burned.', id: 'Surai Api: 90 damage. Lempar koin; jika kepala, lawan terbakar.' }, lore: { en: 'Very smart and vindictive. Grabbing one of its tails could result in a 1000-year curse.', id: 'Sangat cerdas dan pendendam. Menarik ekornya bisa mengakibatkan kutukan 1000 tahun.' }, imageUrl: 'https://placehold.co/400x560/ea580c/ffffff.png?text=Ninetales', color: '#ea580c', hp: 110, attack: 90 },
    { gameId: 'pokemon-tcg', name: { en: 'Growlithe', id: 'Growlithe' }, type: { en: 'Fire - Basic', id: 'Api - Dasar' }, effect: { en: 'Bite: 20 damage.', id: 'Gigitan: 20 damage.' }, lore: { en: 'A friendly and loyal Pokémon that will fearlessly bark at even the largest foe.', id: 'Pokémon yang ramah dan setia, dengan berani menggonggong bahkan ke musuh terbesar.' }, imageUrl: 'https://placehold.co/400x560/f59e0b/ffffff.png?text=Growlithe', color: '#f59e0b', hp: 70, attack: 20 },
    { gameId: 'pokemon-tcg', name: { en: 'Growlithe', id: 'Growlithe' }, type: { en: 'Fire - Basic', id: 'Api - Dasar' }, effect: { en: 'Bite: 20 damage.', id: 'Gigitan: 20 damage.' }, lore: { en: 'A friendly and loyal Pokémon that will fearlessly bark at even the largest foe.', id: 'Pokémon yang ramah dan setia, dengan berani menggonggong bahkan ke musuh terbesar.' }, imageUrl: 'https://placehold.co/400x560/f59e0b/ffffff.png?text=Growlithe', color: '#f59e0b', hp: 70, attack: 20 },
    { gameId: 'pokemon-tcg', name: { en: 'Arcanine', id: 'Arcanine' }, type: { en: 'Fire - Stage 1', id: 'Api - Tahap 1' }, effect: { en: 'Heat Tackle: 120 damage. This Pokémon takes 20 damage.', id: 'Tekel Api: 120 damage. Pokémon ini menerima 20 damage.' }, lore: { en: 'Majestic and swift, it has been admired by people since the past.', id: 'Megah dan cepat, sudah dikagumi manusia sejak dahulu.' }, imageUrl: 'https://placehold.co/400x560/c2410c/ffffff.png?text=Arcanine', color: '#c2410c', hp: 130, attack: 120 },
    { gameId: 'pokemon-tcg', name: { en: 'Ponyta', id: 'Ponyta' }, type: { en: 'Fire - Basic', id: 'Api - Dasar' }, effect: { en: 'Flame Charge: 20 damage. Search deck for 1 Fire Energy and attach it.', id: 'Muatan Api: 20 damage. Cari dek untuk 1 Energi Api dan tempelkan.' }, lore: { en: 'Its hooves are 10 times harder than diamonds. It can trample anything flat.', id: 'Kukunya 10 kali lebih keras dari berlian.' }, imageUrl: 'https://placehold.co/400x560/fb923c/ffffff.png?text=Ponyta', color: '#fb923c', hp: 60, attack: 20 },
    { gameId: 'pokemon-tcg', name: { en: 'Rapidash', id: 'Rapidash' }, type: { en: 'Fire - Stage 1', id: 'Api - Tahap 1' }, effect: { en: 'Agility: 60 damage. Flip coin; if heads, prevent all damage next turn.', id: 'Kelincahan: 60 damage. Lempar koin; jika kepala, cegah semua damage giliran berikutnya.' }, lore: { en: 'At full gallop, its mane and tail blaze so magnificently.', id: 'Saat berlari penuh, surai dan ekornya berkobar dengan megah.' }, imageUrl: 'https://placehold.co/400x560/e11d48/ffffff.png?text=Rapidash', color: '#e11d48', hp: 100, attack: 60 },
    // ─── FIGHTING POKÉMON ───
    { gameId: 'pokemon-tcg', name: { en: 'Machop', id: 'Machop' }, type: { en: 'Fighting - Basic', id: 'Pertarungan - Dasar' }, effect: { en: 'Low Kick: 20 damage.', id: 'Tendangan Rendah: 20 damage.' }, lore: { en: 'Always training in some form of martial art, it is very strong for its size.', id: 'Selalu berlatih bela diri, sangat kuat untuk ukurannya.' }, imageUrl: 'https://placehold.co/400x560/92400e/fef3c7.png?text=Machop', color: '#b45309', hp: 70, attack: 20 },
    { gameId: 'pokemon-tcg', name: { en: 'Machop', id: 'Machop' }, type: { en: 'Fighting - Basic', id: 'Pertarungan - Dasar' }, effect: { en: 'Low Kick: 20 damage.', id: 'Tendangan Rendah: 20 damage.' }, lore: { en: 'Always training in some form of martial art, it is very strong for its size.', id: 'Selalu berlatih bela diri, sangat kuat untuk ukurannya.' }, imageUrl: 'https://placehold.co/400x560/92400e/fef3c7.png?text=Machop', color: '#b45309', hp: 70, attack: 20 },
    { gameId: 'pokemon-tcg', name: { en: 'Machoke', id: 'Machoke' }, type: { en: 'Fighting - Stage 1', id: 'Pertarungan - Tahap 1' }, effect: { en: 'Cross Chop: 60 damage. Flip coin; if heads, 30 more damage.', id: 'Tebas Silang: 60 damage. Lempar koin; jika kepala, 30 damage tambahan.' }, lore: { en: 'It happily carries heavy cargo to earn its keep.', id: 'Dengan senang hati membawa kargo berat untuk mencari nafkah.' }, imageUrl: 'https://placehold.co/400x560/78350f/fef3c7.png?text=Machoke', color: '#a16207', hp: 100, attack: 60 },
    { gameId: 'pokemon-tcg', name: { en: 'Machamp', id: 'Machamp' }, type: { en: 'Fighting - Stage 2', id: 'Pertarungan - Tahap 2' }, effect: { en: 'Seismic Toss: 130 damage.', id: 'Lemparan Seismik: 130 damage.' }, lore: { en: 'One arm alone can move mountains. Using all four arms, it finishes foes with a flurry.', id: 'Satu lengan saja bisa memindahkan gunung. Menggunakan keempat lengannya, ia menghabisi lawan.' }, imageUrl: 'https://placehold.co/400x560/713f12/fef3c7.png?text=Machamp', color: '#854d0e', hp: 160, attack: 130 },
    { gameId: 'pokemon-tcg', name: { en: 'Hitmonlee', id: 'Hitmonlee' }, type: { en: 'Fighting - Basic', id: 'Pertarungan - Dasar' }, effect: { en: 'Stretch Kick: Deal 30 damage to 1 Benched Pokémon.', id: 'Tendangan Jangkau: Berikan 30 damage ke 1 Pokémon di Bench.' }, lore: { en: 'Its legs can stretch double their normal length for devastating kicks.', id: 'Kakinya bisa memanjang dua kali lipat untuk tendangan dahsyat.' }, imageUrl: 'https://placehold.co/400x560/92400e/fef3c7.png?text=Hitmonlee', color: '#b45309', hp: 90, attack: 50 },
    // ─── TRAINER CARDS ───
    { gameId: 'pokemon-tcg', name: { en: 'Professor\'s Research', id: 'Riset Profesor' }, type: { en: 'Trainer - Supporter', id: 'Trainer - Pendukung' }, effect: { en: 'Discard your hand and draw 7 cards.', id: 'Buang tangan Anda dan ambil 7 kartu.' }, lore: { en: 'Professor\'s research is crucial for any trainer\'s journey.', id: 'Riset Profesor sangat penting untuk perjalanan setiap pelatih.' }, imageUrl: 'https://placehold.co/400x560/2563eb/ffffff.png?text=Professor', color: '#2563eb', mana: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Professor\'s Research', id: 'Riset Profesor' }, type: { en: 'Trainer - Supporter', id: 'Trainer - Pendukung' }, effect: { en: 'Discard your hand and draw 7 cards.', id: 'Buang tangan Anda dan ambil 7 kartu.' }, lore: { en: 'Professor\'s research is crucial for any trainer\'s journey.', id: 'Riset Profesor sangat penting untuk perjalanan setiap pelatih.' }, imageUrl: 'https://placehold.co/400x560/2563eb/ffffff.png?text=Professor', color: '#2563eb', mana: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Boss\'s Orders', id: 'Perintah Bos' }, type: { en: 'Trainer - Supporter', id: 'Trainer - Pendukung' }, effect: { en: 'Switch one of your opponent\'s Benched Pokémon with their Active Pokémon.', id: 'Tukar satu Pokémon Bench lawan dengan Pokémon Aktif mereka.' }, lore: { en: 'The boss always gets what the boss wants.', id: 'Bos selalu mendapatkan apa yang bos inginkan.' }, imageUrl: 'https://placehold.co/400x560/1d4ed8/ffffff.png?text=Boss+Orders', color: '#1d4ed8', mana: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Boss\'s Orders', id: 'Perintah Bos' }, type: { en: 'Trainer - Supporter', id: 'Trainer - Pendukung' }, effect: { en: 'Switch one of your opponent\'s Benched Pokémon with their Active Pokémon.', id: 'Tukar satu Pokémon Bench lawan dengan Pokémon Aktif mereka.' }, lore: { en: 'The boss always gets what the boss wants.', id: 'Bos selalu mendapatkan apa yang bos inginkan.' }, imageUrl: 'https://placehold.co/400x560/1d4ed8/ffffff.png?text=Boss+Orders', color: '#1d4ed8', mana: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Nest Ball', id: 'Nest Ball' }, type: { en: 'Trainer - Item', id: 'Trainer - Item' }, effect: { en: 'Search your deck for a Basic Pokémon and put it onto your Bench.', id: 'Cari dek Anda untuk Pokémon Dasar dan letakkan di Bench.' }, lore: { en: 'A comfortable ball that makes wild Pokémon easy to catch.', id: 'Bola nyaman yang memudahkan menangkap Pokémon liar.' }, imageUrl: 'https://placehold.co/400x560/4f46e5/ffffff.png?text=Nest+Ball', color: '#4f46e5', mana: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Nest Ball', id: 'Nest Ball' }, type: { en: 'Trainer - Item', id: 'Trainer - Item' }, effect: { en: 'Search your deck for a Basic Pokémon and put it onto your Bench.', id: 'Cari dek Anda untuk Pokémon Dasar dan letakkan di Bench.' }, lore: { en: 'A comfortable ball that makes wild Pokémon easy to catch.', id: 'Bola nyaman yang memudahkan menangkap Pokémon liar.' }, imageUrl: 'https://placehold.co/400x560/4f46e5/ffffff.png?text=Nest+Ball', color: '#4f46e5', mana: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Rare Candy', id: 'Permen Langka' }, type: { en: 'Trainer - Item', id: 'Trainer - Item' }, effect: { en: 'Choose a Basic Pokémon and put a Stage 2 card on it. (Skip Stage 1)', id: 'Pilih Pokémon Dasar dan letakkan kartu Tahap 2 di atasnya. (Lewati Tahap 1)' }, lore: { en: 'A candy that is packed with energy. Very rare and hard to find.', id: 'Permen yang penuh energi. Sangat langka dan sulit ditemukan.' }, imageUrl: 'https://placehold.co/400x560/7c3aed/ffffff.png?text=Rare+Candy', color: '#7c3aed', mana: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Rare Candy', id: 'Permen Langka' }, type: { en: 'Trainer - Item', id: 'Trainer - Item' }, effect: { en: 'Choose a Basic Pokémon and put a Stage 2 card on it. (Skip Stage 1)', id: 'Pilih Pokémon Dasar dan letakkan kartu Tahap 2 di atasnya. (Lewati Tahap 1)' }, lore: { en: 'A candy that is packed with energy. Very rare and hard to find.', id: 'Permen yang penuh energi. Sangat langka dan sulit ditemukan.' }, imageUrl: 'https://placehold.co/400x560/7c3aed/ffffff.png?text=Rare+Candy', color: '#7c3aed', mana: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Switch', id: 'Tukar' }, type: { en: 'Trainer - Item', id: 'Trainer - Item' }, effect: { en: 'Switch your Active Pokémon with 1 of your Benched Pokémon.', id: 'Tukar Pokémon Aktif Anda dengan 1 Pokémon di Bench.' }, lore: { en: 'A strategic retreat is not the same as running away.', id: 'Mundur strategis tidak sama dengan melarikan diri.' }, imageUrl: 'https://placehold.co/400x560/6366f1/ffffff.png?text=Switch', color: '#6366f1', mana: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Switch', id: 'Tukar' }, type: { en: 'Trainer - Item', id: 'Trainer - Item' }, effect: { en: 'Switch your Active Pokémon with 1 of your Benched Pokémon.', id: 'Tukar Pokémon Aktif Anda dengan 1 Pokémon di Bench.' }, lore: { en: 'A strategic retreat is not the same as running away.', id: 'Mundur strategis tidak sama dengan melarikan diri.' }, imageUrl: 'https://placehold.co/400x560/6366f1/ffffff.png?text=Switch', color: '#6366f1', mana: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Potion', id: 'Ramuan' }, type: { en: 'Trainer - Item', id: 'Trainer - Item' }, effect: { en: 'Heal 30 damage from one of your Pokémon.', id: 'Sembuhkan 30 damage dari salah satu Pokémon Anda.' }, lore: { en: 'A spray-type medicine. It restores HP of one Pokémon.', id: 'Obat tipe semprot. Memulihkan HP satu Pokémon.' }, imageUrl: 'https://placehold.co/400x560/06b6d4/ffffff.png?text=Potion', color: '#06b6d4', mana: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Potion', id: 'Ramuan' }, type: { en: 'Trainer - Item', id: 'Trainer - Item' }, effect: { en: 'Heal 30 damage from one of your Pokémon.', id: 'Sembuhkan 30 damage dari salah satu Pokémon Anda.' }, lore: { en: 'A spray-type medicine. It restores HP of one Pokémon.', id: 'Obat tipe semprot. Memulihkan HP satu Pokémon.' }, imageUrl: 'https://placehold.co/400x560/06b6d4/ffffff.png?text=Potion', color: '#06b6d4', mana: 0 },
    // ─── ENERGY CARDS ───
    { gameId: 'pokemon-tcg', name: { en: 'Fire Energy', id: 'Energi Api' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Fire Energy.', id: 'Memberikan 1 Energi Api.' }, lore: { en: 'The burning essence fuels fire-type attacks.', id: 'Esensi membara sebagai bahan bakar serangan tipe api.' }, imageUrl: 'https://placehold.co/400x560/ef4444/ffffff.png?text=🔥+Energy', color: '#ef4444', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Fire Energy', id: 'Energi Api' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Fire Energy.', id: 'Memberikan 1 Energi Api.' }, lore: { en: 'The burning essence fuels fire-type attacks.', id: 'Esensi membara sebagai bahan bakar serangan tipe api.' }, imageUrl: 'https://placehold.co/400x560/ef4444/ffffff.png?text=🔥+Energy', color: '#ef4444', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Fire Energy', id: 'Energi Api' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Fire Energy.', id: 'Memberikan 1 Energi Api.' }, lore: { en: 'The burning essence fuels fire-type attacks.', id: 'Esensi membara sebagai bahan bakar serangan tipe api.' }, imageUrl: 'https://placehold.co/400x560/ef4444/ffffff.png?text=🔥+Energy', color: '#ef4444', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Fire Energy', id: 'Energi Api' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Fire Energy.', id: 'Memberikan 1 Energi Api.' }, lore: { en: 'The burning essence fuels fire-type attacks.', id: 'Esensi membara sebagai bahan bakar serangan tipe api.' }, imageUrl: 'https://placehold.co/400x560/ef4444/ffffff.png?text=🔥+Energy', color: '#ef4444', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Fire Energy', id: 'Energi Api' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Fire Energy.', id: 'Memberikan 1 Energi Api.' }, lore: { en: 'The burning essence fuels fire-type attacks.', id: 'Esensi membara sebagai bahan bakar serangan tipe api.' }, imageUrl: 'https://placehold.co/400x560/ef4444/ffffff.png?text=🔥+Energy', color: '#ef4444', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Fire Energy', id: 'Energi Api' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Fire Energy.', id: 'Memberikan 1 Energi Api.' }, lore: { en: 'The burning essence fuels fire-type attacks.', id: 'Esensi membara sebagai bahan bakar serangan tipe api.' }, imageUrl: 'https://placehold.co/400x560/ef4444/ffffff.png?text=🔥+Energy', color: '#ef4444', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Fire Energy', id: 'Energi Api' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Fire Energy.', id: 'Memberikan 1 Energi Api.' }, lore: { en: 'The burning essence fuels fire-type attacks.', id: 'Esensi membara sebagai bahan bakar serangan tipe api.' }, imageUrl: 'https://placehold.co/400x560/ef4444/ffffff.png?text=🔥+Energy', color: '#ef4444', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Fire Energy', id: 'Energi Api' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Fire Energy.', id: 'Memberikan 1 Energi Api.' }, lore: { en: 'The burning essence fuels fire-type attacks.', id: 'Esensi membara sebagai bahan bakar serangan tipe api.' }, imageUrl: 'https://placehold.co/400x560/ef4444/ffffff.png?text=🔥+Energy', color: '#ef4444', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Fire Energy', id: 'Energi Api' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Fire Energy.', id: 'Memberikan 1 Energi Api.' }, lore: { en: 'The burning essence fuels fire-type attacks.', id: 'Esensi membara sebagai bahan bakar serangan tipe api.' }, imageUrl: 'https://placehold.co/400x560/ef4444/ffffff.png?text=🔥+Energy', color: '#ef4444', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Fire Energy', id: 'Energi Api' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Fire Energy.', id: 'Memberikan 1 Energi Api.' }, lore: { en: 'The burning essence fuels fire-type attacks.', id: 'Esensi membara sebagai bahan bakar serangan tipe api.' }, imageUrl: 'https://placehold.co/400x560/ef4444/ffffff.png?text=🔥+Energy', color: '#ef4444', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Fighting Energy', id: 'Energi Pertarungan' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Fighting Energy.', id: 'Memberikan 1 Energi Pertarungan.' }, lore: { en: 'Raw strength condensed into pure energy.', id: 'Kekuatan mentah terkondensasi menjadi energi murni.' }, imageUrl: 'https://placehold.co/400x560/b45309/ffffff.png?text=⚔+Energy', color: '#b45309', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Fighting Energy', id: 'Energi Pertarungan' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Fighting Energy.', id: 'Memberikan 1 Energi Pertarungan.' }, lore: { en: 'Raw strength condensed into pure energy.', id: 'Kekuatan mentah terkondensasi menjadi energi murni.' }, imageUrl: 'https://placehold.co/400x560/b45309/ffffff.png?text=⚔+Energy', color: '#b45309', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Fighting Energy', id: 'Energi Pertarungan' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Fighting Energy.', id: 'Memberikan 1 Energi Pertarungan.' }, lore: { en: 'Raw strength condensed into pure energy.', id: 'Kekuatan mentah terkondensasi menjadi energi murni.' }, imageUrl: 'https://placehold.co/400x560/b45309/ffffff.png?text=⚔+Energy', color: '#b45309', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Fighting Energy', id: 'Energi Pertarungan' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Fighting Energy.', id: 'Memberikan 1 Energi Pertarungan.' }, lore: { en: 'Raw strength condensed into pure energy.', id: 'Kekuatan mentah terkondensasi menjadi energi murni.' }, imageUrl: 'https://placehold.co/400x560/b45309/ffffff.png?text=⚔+Energy', color: '#b45309', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Fighting Energy', id: 'Energi Pertarungan' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Fighting Energy.', id: 'Memberikan 1 Energi Pertarungan.' }, lore: { en: 'Raw strength condensed into pure energy.', id: 'Kekuatan mentah terkondensasi menjadi energi murni.' }, imageUrl: 'https://placehold.co/400x560/b45309/ffffff.png?text=⚔+Energy', color: '#b45309', mana: 1 },
];

// ──── Starter Deck 2: Tidal Force (Water/Psychic) ────
export const pokemonDeck2Cards = [
    // ─── WATER POKÉMON ───
    { gameId: 'pokemon-tcg', name: { en: 'Squirtle', id: 'Squirtle' }, type: { en: 'Water - Basic', id: 'Air - Dasar' }, effect: { en: 'Water Gun: 20 damage.', id: 'Pistol Air: 20 damage.' }, lore: { en: 'Shoots water at prey while hiding in its shell.', id: 'Menembakkan air ke mangsa sambil bersembunyi di cangkangnya.' }, imageUrl: 'https://placehold.co/400x560/3b82f6/ffffff.png?text=Squirtle', color: '#3b82f6', hp: 70, attack: 20 },
    { gameId: 'pokemon-tcg', name: { en: 'Squirtle', id: 'Squirtle' }, type: { en: 'Water - Basic', id: 'Air - Dasar' }, effect: { en: 'Water Gun: 20 damage.', id: 'Pistol Air: 20 damage.' }, lore: { en: 'Shoots water at prey while hiding in its shell.', id: 'Menembakkan air ke mangsa sambil bersembunyi di cangkangnya.' }, imageUrl: 'https://placehold.co/400x560/3b82f6/ffffff.png?text=Squirtle', color: '#3b82f6', hp: 70, attack: 20 },
    { gameId: 'pokemon-tcg', name: { en: 'Wartortle', id: 'Wartortle' }, type: { en: 'Water - Stage 1', id: 'Air - Tahap 1' }, effect: { en: 'Aqua Tail: 50 damage. Flip coin; if heads, 30 more.', id: 'Ekor Aqua: 50 damage. Lempar koin; jika kepala, 30 tambahan.' }, lore: { en: 'Its large tail is covered with fur that can absorb water to aid in swimming.', id: 'Ekornya yang besar ditutupi bulu yang bisa menyerap air.' }, imageUrl: 'https://placehold.co/400x560/2563eb/ffffff.png?text=Wartortle', color: '#2563eb', hp: 90, attack: 50 },
    { gameId: 'pokemon-tcg', name: { en: 'Blastoise', id: 'Blastoise' }, type: { en: 'Water - Stage 2', id: 'Air - Tahap 2' }, effect: { en: 'Ability: Torrential Cannon — Attach up to 2 Water Energy from hand. Hydro Pump: 160 damage.', id: 'Kemampuan: Meriam Torrensial — Tempelkan 2 Energi Air dari tangan. Pompa Hidro: 160 damage.' }, lore: { en: 'Crushes foes with the water jets on its shell at close range.', id: 'Menghancurkan lawan dengan semburan air dari cangkangnya.' }, imageUrl: 'https://placehold.co/400x560/1d4ed8/ffffff.png?text=Blastoise', color: '#1d4ed8', hp: 180, attack: 160 },
    { gameId: 'pokemon-tcg', name: { en: 'Psyduck', id: 'Psyduck' }, type: { en: 'Water - Basic', id: 'Air - Dasar' }, effect: { en: 'Headache: 10 damage. Opponent can\'t play Trainer cards next turn.', id: 'Sakit Kepala: 10 damage. Lawan tidak bisa bermain kartu Trainer giliran berikutnya.' }, lore: { en: 'Always tormented by headaches. It uses psychic powers without even realizing it.', id: 'Selalu disiksa sakit kepala. Menggunakan kekuatan psikis tanpa sadar.' }, imageUrl: 'https://placehold.co/400x560/60a5fa/ffffff.png?text=Psyduck', color: '#60a5fa', hp: 60, attack: 10 },
    { gameId: 'pokemon-tcg', name: { en: 'Psyduck', id: 'Psyduck' }, type: { en: 'Water - Basic', id: 'Air - Dasar' }, effect: { en: 'Headache: 10 damage. Opponent can\'t play Trainer cards next turn.', id: 'Sakit Kepala: 10 damage. Lawan tidak bisa bermain kartu Trainer giliran berikutnya.' }, lore: { en: 'Always tormented by headaches. It uses psychic powers without even realizing it.', id: 'Selalu disiksa sakit kepala. Menggunakan kekuatan psikis tanpa sadar.' }, imageUrl: 'https://placehold.co/400x560/60a5fa/ffffff.png?text=Psyduck', color: '#60a5fa', hp: 60, attack: 10 },
    { gameId: 'pokemon-tcg', name: { en: 'Golduck', id: 'Golduck' }, type: { en: 'Water - Stage 1', id: 'Air - Tahap 1' }, effect: { en: 'Aqua Slash: 70 damage. Can\'t use this attack next turn.', id: 'Tebasan Aqua: 70 damage. Tidak bisa menggunakan serangan ini giliran berikutnya.' }, lore: { en: 'The webbed flippers on its forelegs help propel it through water.', id: 'Sirip berselaput di kaki depannya membantu mendorong melalui air.' }, imageUrl: 'https://placehold.co/400x560/2563eb/ffffff.png?text=Golduck', color: '#2563eb', hp: 100, attack: 70 },
    { gameId: 'pokemon-tcg', name: { en: 'Lapras', id: 'Lapras' }, type: { en: 'Water - Basic', id: 'Air - Dasar' }, effect: { en: 'Ice Beam: 30 damage. Flip coin; if heads, opponent is Paralyzed.', id: 'Sinar Es: 30 damage. Lempar koin; jika kepala, lawan Lumpuh.' }, lore: { en: 'A gentle soul that can understand human speech. It ferries people across the sea.', id: 'Jiwa yang lembut, memahami bahasa manusia. Mengantar orang menyeberangi laut.' }, imageUrl: 'https://placehold.co/400x560/0891b2/ffffff.png?text=Lapras', color: '#0891b2', hp: 120, attack: 30 },
    { gameId: 'pokemon-tcg', name: { en: 'Lapras', id: 'Lapras' }, type: { en: 'Water - Basic', id: 'Air - Dasar' }, effect: { en: 'Ice Beam: 30 damage. Flip coin; if heads, opponent is Paralyzed.', id: 'Sinar Es: 30 damage. Lempar koin; jika kepala, lawan Lumpuh.' }, lore: { en: 'A gentle soul that can understand human speech. It ferries people across the sea.', id: 'Jiwa yang lembut, memahami bahasa manusia. Mengantar orang menyeberangi laut.' }, imageUrl: 'https://placehold.co/400x560/0891b2/ffffff.png?text=Lapras', color: '#0891b2', hp: 120, attack: 30 },
    { gameId: 'pokemon-tcg', name: { en: 'Staryu', id: 'Staryu' }, type: { en: 'Water - Basic', id: 'Air - Dasar' }, effect: { en: 'Swift: 20 damage. This attack\'s damage isn\'t affected by anything.', id: 'Cepat: 20 damage. Damage serangan ini tidak terpengaruh oleh apapun.' }, lore: { en: 'If its body is torn, it can grow back as long as the red core remains.', id: 'Jika tubuhnya robek, bisa tumbuh kembali selama inti merah tetap ada.' }, imageUrl: 'https://placehold.co/400x560/06b6d4/ffffff.png?text=Staryu', color: '#06b6d4', hp: 50, attack: 20 },
    { gameId: 'pokemon-tcg', name: { en: 'Starmie', id: 'Starmie' }, type: { en: 'Water - Stage 1', id: 'Air - Tahap 1' }, effect: { en: 'Star Freeze: 50 damage. Flip coin; if heads, opponent is Paralyzed.', id: 'Bintang Beku: 50 damage. Lempar koin; jika kepala, lawan Lumpuh.' }, lore: { en: 'The core glows in seven colors, earning it the name "Gem of the Sea."', id: 'Intinya bersinar dalam tujuh warna, dijuluki "Permata Laut."' }, imageUrl: 'https://placehold.co/400x560/0284c7/ffffff.png?text=Starmie', color: '#0284c7', hp: 80, attack: 50 },
    // ─── PSYCHIC POKÉMON ───
    { gameId: 'pokemon-tcg', name: { en: 'Abra', id: 'Abra' }, type: { en: 'Psychic - Basic', id: 'Psikis - Dasar' }, effect: { en: 'Teleport: Switch this Pokémon with 1 of your Benched Pokémon.', id: 'Teleportasi: Tukar Pokémon ini dengan 1 Pokémon di Bench Anda.' }, lore: { en: 'Sleeps 18 hours a day. Uses Teleport to flee danger even while asleep.', id: 'Tidur 18 jam sehari. Menggunakan Teleportasi untuk kabur bahkan saat tidur.' }, imageUrl: 'https://placehold.co/400x560/a855f7/ffffff.png?text=Abra', color: '#a855f7', hp: 50, attack: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Abra', id: 'Abra' }, type: { en: 'Psychic - Basic', id: 'Psikis - Dasar' }, effect: { en: 'Teleport: Switch this Pokémon with 1 of your Benched Pokémon.', id: 'Teleportasi: Tukar Pokémon ini dengan 1 Pokémon di Bench Anda.' }, lore: { en: 'Sleeps 18 hours a day. Uses Teleport to flee danger even while asleep.', id: 'Tidur 18 jam sehari. Menggunakan Teleportasi untuk kabur bahkan saat tidur.' }, imageUrl: 'https://placehold.co/400x560/a855f7/ffffff.png?text=Abra', color: '#a855f7', hp: 50, attack: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Kadabra', id: 'Kadabra' }, type: { en: 'Psychic - Stage 1', id: 'Psikis - Tahap 1' }, effect: { en: 'Psybeam: 60 damage. Flip coin; if heads, opponent is Confused.', id: 'Sinar Psikis: 60 damage. Lempar koin; jika kepala, lawan Bingung.' }, lore: { en: 'It emits special alpha waves that induce headaches in anyone nearby.', id: 'Memancarkan gelombang alpha khusus yang menyebabkan sakit kepala.' }, imageUrl: 'https://placehold.co/400x560/9333ea/ffffff.png?text=Kadabra', color: '#9333ea', hp: 80, attack: 60 },
    { gameId: 'pokemon-tcg', name: { en: 'Alakazam', id: 'Alakazam' }, type: { en: 'Psychic - Stage 2', id: 'Psikis - Tahap 2' }, effect: { en: 'Ability: Mind Jack — Move damage counters between your Pokémon. Psychic: 120 damage.', id: 'Kemampuan: Peretasan Pikiran — Pindahkan penanda damage antar Pokémon Anda. Psikis: 120 damage.' }, lore: { en: 'Its IQ is said to be around 5,000. It remembers everything that has ever happened.', id: 'IQ-nya dikatakan sekitar 5.000. Mengingat semua yang pernah terjadi.' }, imageUrl: 'https://placehold.co/400x560/7e22ce/ffffff.png?text=Alakazam', color: '#7e22ce', hp: 150, attack: 120 },
    { gameId: 'pokemon-tcg', name: { en: 'Gastly', id: 'Gastly' }, type: { en: 'Psychic - Basic', id: 'Psikis - Dasar' }, effect: { en: 'Lick: 10 damage. Flip coin; if heads, opponent is Paralyzed.', id: 'Jilatan: 10 damage. Lempar koin; jika kepala, lawan Lumpuh.' }, lore: { en: 'Born from gases, anyone would faint if engulfed in its gaseous body.', id: 'Lahir dari gas, siapapun akan pingsan jika terselimuti tubuh gasnya.' }, imageUrl: 'https://placehold.co/400x560/c084fc/ffffff.png?text=Gastly', color: '#c084fc', hp: 50, attack: 10 },
    { gameId: 'pokemon-tcg', name: { en: 'Haunter', id: 'Haunter' }, type: { en: 'Psychic - Stage 1', id: 'Psikis - Tahap 1' }, effect: { en: 'Shadow Punch: 40 damage. This attack\'s damage isn\'t affected by Resistance.', id: 'Pukulan Bayangan: 40 damage. Damage serangan ini tidak terpengaruh Resistansi.' }, lore: { en: 'If you get the feeling of being watched, Haunter is probably there.', id: 'Jika Anda merasa diawasi, Haunter mungkin ada di sana.' }, imageUrl: 'https://placehold.co/400x560/a855f7/ffffff.png?text=Haunter', color: '#a855f7', hp: 70, attack: 40 },
    { gameId: 'pokemon-tcg', name: { en: 'Gengar', id: 'Gengar' }, type: { en: 'Psychic - Stage 2', id: 'Psikis - Tahap 2' }, effect: { en: 'Ability: Cursed Drop — Put 3 damage counters on opponent\'s Pokémon. Night Shade: 110 damage.', id: 'Kemampuan: Jatuhan Kutukan — Letakkan 3 penanda damage ke Pokémon lawan. Bayangan Malam: 110 damage.' }, lore: { en: 'It lurks in the shadows of rooms, waiting for a chance to steal the life force.', id: 'Bersembunyi di bayangan ruangan, menunggu kesempatan mencuri daya hidup.' }, imageUrl: 'https://placehold.co/400x560/6b21a8/ffffff.png?text=Gengar', color: '#6b21a8', hp: 140, attack: 110 },
    // ─── TRAINER CARDS (shared staples) ───
    { gameId: 'pokemon-tcg', name: { en: 'Professor\'s Research', id: 'Riset Profesor' }, type: { en: 'Trainer - Supporter', id: 'Trainer - Pendukung' }, effect: { en: 'Discard your hand and draw 7 cards.', id: 'Buang tangan Anda dan ambil 7 kartu.' }, lore: { en: 'Professor\'s research is crucial for any trainer\'s journey.', id: 'Riset Profesor sangat penting untuk setiap pelatih.' }, imageUrl: 'https://placehold.co/400x560/2563eb/ffffff.png?text=Professor', color: '#2563eb', mana: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Professor\'s Research', id: 'Riset Profesor' }, type: { en: 'Trainer - Supporter', id: 'Trainer - Pendukung' }, effect: { en: 'Discard your hand and draw 7 cards.', id: 'Buang tangan Anda dan ambil 7 kartu.' }, lore: { en: 'Professor\'s research is crucial for any trainer\'s journey.', id: 'Riset Profesor sangat penting untuk setiap pelatih.' }, imageUrl: 'https://placehold.co/400x560/2563eb/ffffff.png?text=Professor', color: '#2563eb', mana: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Boss\'s Orders', id: 'Perintah Bos' }, type: { en: 'Trainer - Supporter', id: 'Trainer - Pendukung' }, effect: { en: 'Switch one of opponent\'s Benched Pokémon with their Active.', id: 'Tukar satu Pokémon Bench lawan dengan Aktif mereka.' }, lore: { en: 'The boss always gets what the boss wants.', id: 'Bos selalu mendapatkan apa yang bos inginkan.' }, imageUrl: 'https://placehold.co/400x560/1d4ed8/ffffff.png?text=Boss+Orders', color: '#1d4ed8', mana: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Nest Ball', id: 'Nest Ball' }, type: { en: 'Trainer - Item', id: 'Trainer - Item' }, effect: { en: 'Search deck for a Basic Pokémon to Bench.', id: 'Cari dek untuk Pokémon Dasar ke Bench.' }, lore: { en: 'A comfortable ball for catching Pokémon.', id: 'Bola nyaman untuk menangkap Pokémon.' }, imageUrl: 'https://placehold.co/400x560/4f46e5/ffffff.png?text=Nest+Ball', color: '#4f46e5', mana: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Nest Ball', id: 'Nest Ball' }, type: { en: 'Trainer - Item', id: 'Trainer - Item' }, effect: { en: 'Search deck for a Basic Pokémon to Bench.', id: 'Cari dek untuk Pokémon Dasar ke Bench.' }, lore: { en: 'A comfortable ball for catching Pokémon.', id: 'Bola nyaman untuk menangkap Pokémon.' }, imageUrl: 'https://placehold.co/400x560/4f46e5/ffffff.png?text=Nest+Ball', color: '#4f46e5', mana: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Rare Candy', id: 'Permen Langka' }, type: { en: 'Trainer - Item', id: 'Trainer - Item' }, effect: { en: 'Put a Stage 2 on a Basic (skip Stage 1).', id: 'Letakkan Tahap 2 di atas Dasar (lewati Tahap 1).' }, lore: { en: 'A rare and energy-packed candy.', id: 'Permen langka dan penuh energi.' }, imageUrl: 'https://placehold.co/400x560/7c3aed/ffffff.png?text=Rare+Candy', color: '#7c3aed', mana: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Rare Candy', id: 'Permen Langka' }, type: { en: 'Trainer - Item', id: 'Trainer - Item' }, effect: { en: 'Put a Stage 2 on a Basic (skip Stage 1).', id: 'Letakkan Tahap 2 di atas Dasar (lewati Tahap 1).' }, lore: { en: 'A rare and energy-packed candy.', id: 'Permen langka dan penuh energi.' }, imageUrl: 'https://placehold.co/400x560/7c3aed/ffffff.png?text=Rare+Candy', color: '#7c3aed', mana: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Switch', id: 'Tukar' }, type: { en: 'Trainer - Item', id: 'Trainer - Item' }, effect: { en: 'Switch your Active Pokémon with 1 Benched.', id: 'Tukar Pokémon Aktif dengan 1 di Bench.' }, lore: { en: 'A strategic retreat.', id: 'Mundur strategis.' }, imageUrl: 'https://placehold.co/400x560/6366f1/ffffff.png?text=Switch', color: '#6366f1', mana: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Switch', id: 'Tukar' }, type: { en: 'Trainer - Item', id: 'Trainer - Item' }, effect: { en: 'Switch your Active Pokémon with 1 Benched.', id: 'Tukar Pokémon Aktif dengan 1 di Bench.' }, lore: { en: 'A strategic retreat.', id: 'Mundur strategis.' }, imageUrl: 'https://placehold.co/400x560/6366f1/ffffff.png?text=Switch', color: '#6366f1', mana: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Super Potion', id: 'Ramuan Super' }, type: { en: 'Trainer - Item', id: 'Trainer - Item' }, effect: { en: 'Discard 1 Energy from your Pokémon. Heal 60 damage.', id: 'Buang 1 Energi dari Pokémon Anda. Sembuhkan 60 damage.' }, lore: { en: 'An upgraded potion with stronger healing.', id: 'Ramuan yang ditingkatkan dengan penyembuhan lebih kuat.' }, imageUrl: 'https://placehold.co/400x560/06b6d4/ffffff.png?text=Super+Potion', color: '#06b6d4', mana: 0 },
    { gameId: 'pokemon-tcg', name: { en: 'Super Potion', id: 'Ramuan Super' }, type: { en: 'Trainer - Item', id: 'Trainer - Item' }, effect: { en: 'Discard 1 Energy from your Pokémon. Heal 60 damage.', id: 'Buang 1 Energi dari Pokémon Anda. Sembuhkan 60 damage.' }, lore: { en: 'An upgraded potion with stronger healing.', id: 'Ramuan yang ditingkatkan dengan penyembuhan lebih kuat.' }, imageUrl: 'https://placehold.co/400x560/06b6d4/ffffff.png?text=Super+Potion', color: '#06b6d4', mana: 0 },
    // ─── ENERGY CARDS ───
    { gameId: 'pokemon-tcg', name: { en: 'Water Energy', id: 'Energi Air' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Water Energy.', id: 'Memberikan 1 Energi Air.' }, lore: { en: 'The flowing essence powers water-type attacks.', id: 'Esensi mengalir sebagai tenaga serangan tipe air.' }, imageUrl: 'https://placehold.co/400x560/3b82f6/ffffff.png?text=💧+Energy', color: '#3b82f6', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Water Energy', id: 'Energi Air' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Water Energy.', id: 'Memberikan 1 Energi Air.' }, lore: { en: 'The flowing essence powers water-type attacks.', id: 'Esensi mengalir sebagai tenaga serangan tipe air.' }, imageUrl: 'https://placehold.co/400x560/3b82f6/ffffff.png?text=💧+Energy', color: '#3b82f6', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Water Energy', id: 'Energi Air' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Water Energy.', id: 'Memberikan 1 Energi Air.' }, lore: { en: 'The flowing essence powers water-type attacks.', id: 'Esensi mengalir sebagai tenaga serangan tipe air.' }, imageUrl: 'https://placehold.co/400x560/3b82f6/ffffff.png?text=💧+Energy', color: '#3b82f6', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Water Energy', id: 'Energi Air' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Water Energy.', id: 'Memberikan 1 Energi Air.' }, lore: { en: 'The flowing essence powers water-type attacks.', id: 'Esensi mengalir sebagai tenaga serangan tipe air.' }, imageUrl: 'https://placehold.co/400x560/3b82f6/ffffff.png?text=💧+Energy', color: '#3b82f6', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Water Energy', id: 'Energi Air' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Water Energy.', id: 'Memberikan 1 Energi Air.' }, lore: { en: 'The flowing essence powers water-type attacks.', id: 'Esensi mengalir sebagai tenaga serangan tipe air.' }, imageUrl: 'https://placehold.co/400x560/3b82f6/ffffff.png?text=💧+Energy', color: '#3b82f6', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Water Energy', id: 'Energi Air' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Water Energy.', id: 'Memberikan 1 Energi Air.' }, lore: { en: 'The flowing essence powers water-type attacks.', id: 'Esensi mengalir sebagai tenaga serangan tipe air.' }, imageUrl: 'https://placehold.co/400x560/3b82f6/ffffff.png?text=💧+Energy', color: '#3b82f6', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Water Energy', id: 'Energi Air' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Water Energy.', id: 'Memberikan 1 Energi Air.' }, lore: { en: 'The flowing essence powers water-type attacks.', id: 'Esensi mengalir sebagai tenaga serangan tipe air.' }, imageUrl: 'https://placehold.co/400x560/3b82f6/ffffff.png?text=💧+Energy', color: '#3b82f6', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Water Energy', id: 'Energi Air' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Water Energy.', id: 'Memberikan 1 Energi Air.' }, lore: { en: 'The flowing essence powers water-type attacks.', id: 'Esensi mengalir sebagai tenaga serangan tipe air.' }, imageUrl: 'https://placehold.co/400x560/3b82f6/ffffff.png?text=💧+Energy', color: '#3b82f6', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Water Energy', id: 'Energi Air' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Water Energy.', id: 'Memberikan 1 Energi Air.' }, lore: { en: 'The flowing essence powers water-type attacks.', id: 'Esensi mengalir sebagai tenaga serangan tipe air.' }, imageUrl: 'https://placehold.co/400x560/3b82f6/ffffff.png?text=💧+Energy', color: '#3b82f6', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Psychic Energy', id: 'Energi Psikis' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Psychic Energy.', id: 'Memberikan 1 Energi Psikis.' }, lore: { en: 'Mysterious energy fueling mental powers.', id: 'Energi misterius yang memberi tenaga kekuatan mental.' }, imageUrl: 'https://placehold.co/400x560/a855f7/ffffff.png?text=🔮+Energy', color: '#a855f7', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Psychic Energy', id: 'Energi Psikis' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Psychic Energy.', id: 'Memberikan 1 Energi Psikis.' }, lore: { en: 'Mysterious energy fueling mental powers.', id: 'Energi misterius yang memberi tenaga kekuatan mental.' }, imageUrl: 'https://placehold.co/400x560/a855f7/ffffff.png?text=🔮+Energy', color: '#a855f7', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Psychic Energy', id: 'Energi Psikis' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Psychic Energy.', id: 'Memberikan 1 Energi Psikis.' }, lore: { en: 'Mysterious energy fueling mental powers.', id: 'Energi misterius yang memberi tenaga kekuatan mental.' }, imageUrl: 'https://placehold.co/400x560/a855f7/ffffff.png?text=🔮+Energy', color: '#a855f7', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Psychic Energy', id: 'Energi Psikis' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Psychic Energy.', id: 'Memberikan 1 Energi Psikis.' }, lore: { en: 'Mysterious energy fueling mental powers.', id: 'Energi misterius yang memberi tenaga kekuatan mental.' }, imageUrl: 'https://placehold.co/400x560/a855f7/ffffff.png?text=🔮+Energy', color: '#a855f7', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Psychic Energy', id: 'Energi Psikis' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Psychic Energy.', id: 'Memberikan 1 Energi Psikis.' }, lore: { en: 'Mysterious energy fueling mental powers.', id: 'Energi misterius yang memberi tenaga kekuatan mental.' }, imageUrl: 'https://placehold.co/400x560/a855f7/ffffff.png?text=🔮+Energy', color: '#a855f7', mana: 1 },
    { gameId: 'pokemon-tcg', name: { en: 'Psychic Energy', id: 'Energi Psikis' }, type: { en: 'Energy - Basic', id: 'Energi - Dasar' }, effect: { en: 'Provides 1 Psychic Energy.', id: 'Memberikan 1 Energi Psikis.' }, lore: { en: 'Mysterious energy fueling mental powers.', id: 'Energi misterius yang memberi tenaga kekuatan mental.' }, imageUrl: 'https://placehold.co/400x560/a855f7/ffffff.png?text=🔮+Energy', color: '#a855f7', mana: 1 },
];
